[package]
name = "bookmarks"
version = "0.1.0"
edition = "2021"

[lib]
name = "_native"
path = "native/src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["abi3-py311", "extension-module"] }
